### ISSUE TITLE
serveOnly cannot parse my intern.json even though it is valid

### ISSUE THREAD

**Issue by schontz** [theintern/intern#947]
## Expected behavior
My `intern.json` file would be parsed and I can run my tests in the browser.

## Current behavior
DevTools shows the following error:
```
(index):52 Error initializing Intern: Error: Invalid JSON in /intern.json
    at config.js:16
    at config.js:16
```

## Possible solution
After some digging around it appears that JSON.parse is being given a promise, which becomes `[object ArrayBuffer]` and cannot be parsed.

** Until this is fixed you can use 4.2.x and it works!**

## Steps to reproduce (for bugs)
1. Run `npx intern serveOnly`
2. Browse to the web page
3. View DevTools

## Environment

Intern version: 4.3.0
Browser version: Chrome 69.0.3497.92
OS: Windows 10

## Additional information
Running `npx intern` works. This issue just happens with `serveOnly` or visiting `node_modules/intern` on the local dev server.

I spoke with @jason0x43 about it.

**Comment by schontz** [comment]
In case you are running into this issue just downgrade to Intern 4.2.x until this bug is closed.

**Comment by jason0x43** [comment]
This was due to a bug in @theintern/common, and was fixed in v0.1.1.

**Comment by schontz** [comment]
Great! This fix will be available in intern 4.3.1 then?

**Comment by jason0x43** [comment]
It was a bugfix to one of Intern's dependencies, so if you reinstall Intern you should have it.

**Comment by schontz** [comment]
Reinstalled intern, confirmed `intern` is at `4.3.0` and `@theintern/common` is at `0.1.1` and the problem persists.

**Comment by jason0x43** [comment]
Hmmm...maybe I missed something while testing. I’ll take another look. Just to make sure, were the dependencies for digdug and leadfoot deduped, so that there is only one installed version of common?

**Comment by jason0x43** [comment]
`npm rm intern && npm install intern@latest`. That will uninstall Intern and all its dependencies, and remove them from the package-lock file, then re-install them.

**Comment by schontz** [comment]
Ran those and the issue persists. 

```
`-- intern@4.3.0
  +-- @theintern/common@0.1.1
  +-- @theintern/digdug@2.2.0
  | `-- @theintern/common@0.1.1  deduped
  `-- @theintern/leadfoot@2.2.0
    `-- @theintern/common@0.1.1  deduped
```

**Comment by jason0x43** [comment]
Ah ha! I think I found the issue. It wasn't a problem with the code this time, but with the built webpack bundle. webpack was adding polyfills for node builtins and was breaking some explicit type checks.

**Comment by schontz** [comment]
Great. I tried running 4.3.0 again and it still failed. I assume there's something that needs to be updated in npm or elsewhere first?

**Comment by jason0x43** [comment]
Update to 4.3.1

**Comment by jason0x43** [comment]
That brings in updated common, digdug, and leadfoot dependencies.

**Comment by schontz** [comment]
Yay! It works!
